import { config } from "dotenv"
import { defineConfig } from "drizzle-kit"

// drizzle-kit runs outside Next, so nothing has loaded .env.local for it.
config({ path: ".env.local" })

export default defineConfig({
  // Two files: schema.ts is generated by `pnpm auth:generate` and must not be
  // hand-edited; schema-app.ts is ours.
  schema: ["./lib/schema.ts", "./lib/schema-app.ts"],
  out: "./drizzle",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
  strict: true,
  verbose: true,
})
